### ISSUE TITLE
Working with Contentful access_token

### ISSUE THREAD

**Issue by Gioni06** [javaporter/roots-contentful-foundation#8]
Hi, i would suggest to put your access_token into a node enviroment variable like

```
contentful
      access_token: process.env.TOKEN
      space_id: '2xk63okczz9t'
      content_types:
        blog_posts:
          id: '1fUnrMgZL8WeSu26AYQyOY'
          template: 'views/_single.jade'
          path: (e) -> "blog/#{slugify(e.title)}"
```
For development i use this alongside with https://www.npmjs.com/package/dotenv
and add the .env file to my .gitignore and `ignores` in `app.coffee` works great for me.

If you like, you can have a look at my repo https://github.com/Gioni06/personal-site . I'm really starting to dick into roots and contenful now and i would appreciate any feedback.
